### ISSUE TITLE
InputManager

### ISSUE THREAD

**Issue by DarKDevz** [HasangerGames/suroi#107]
**Describe the bug**
Part1:
on inputmanager.ts 
at handleInput
modifierCount
modifierCount no matter how many modifiers are there it will never be above 1
Part2:
  if you press a, then shift(or any meta key) then unpress a
  you wont stop moving even if there are no keys pressed
  this might be because it makes the event.key an uppercase value
  i tried seeing where the code screws up but it seems to be accounted for but it isn't
  **Expected behavior**
  if you press shift and alt you will see that modifierCount remains at 1
  because a switch statement is used for some weird reason
  and "break;" exits the switch statement and doesn't increase the modifier further

i would just use a series of if statement even though it doesn't look nice
or just remove break; as it isn't needed in this case  
also is this makes the modifiercount go over one the check to see if any of the meta keys are in the event.key isn't needed
as event.shiftKey altKey etc.. is turned down even if the only main input

**Desktop :**
 - Browser [e.g. chrome]

**Comment by Killaship** [comment]
I guess I'll take a poke at this

**Comment by Killaship** [comment]
nevermind, appears @ei-pi is on it
