### ISSUE TITLE
Mouse Input

### ISSUE THREAD

**Issue by DarKDevz** [HasangerGames/suroi#109]
1:
on the original surviv.io pressing the mouse once and holding it will keep the player punching
here you have to keep pressing the mouse and even then you have a delay between clicks
2:
if you are shooting then you switch weapons (from automatic to automatic)
you will not keep shooting and you have to wait for the delay then press down the mouse again

**Desktop :**
 - OS: [iOS]
 - Browser [chrome]

**Comment by Katloo24** [comment]
for number 1 im like 99% sure that it was not the case

**Comment by ei-pi** [comment]
it was not lmao
the only melee weapon that attacked in an automatic fashion(similar to an automatic weapon) was the hook

as for number two, I'm not really sure how that's a bug, considering that the sequence of events listed is basically just what switch delay is

**Comment by Katloo24** [comment]
wait they said desktop but also said ios, does that mean they are talking about mobile? I'm pretty sure it auto punches on mobile rn

**Comment by DarKDevz** [comment]
Idk, i player surviv in 2016to2018 it just looked awkward having a delay on punching, as i have unstable connection sometimes it took even seconds to punch another time, about the gun delay, shouldn't it wait for the gun then keep shooting? and yes it's not ios but MacOs my fault i didn't change the bug report template

**Comment by ei-pi** [comment]
> about the gun delay, shouldn't it wait for the gun then keep shooting

what does this sentence mean
and if possible, could we continue this discussion in the discord server?

**Comment by hsanger** [comment]
https://discord.suroi.io
