### ISSUE TITLE
Unable to attack with joystick size of 100 or under

### ISSUE THREAD

**Issue by valtsu41** [HasangerGames/suroi#112]
**Describe the bug**
Attacking doesn't seem to work when joystick size is 100 or under.

**To Reproduce**
1. Set joystick size to 100 or under on mobile.
2. Try to attack.

**Expected behavior**
Being able to attack with any joystick size setting.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Android
 - Browser: Tested on Chrome and Samsung Internet 
 - Version: Chrome 116.0.5845.114, Samsung Internet 19.0.3.12

**Additional context**
Tested on two different devices.

**Comment by hsanger** [comment]
Fixed!
