### ISSUE TITLE
The water tank texture is rounded although it's hitbox is not.

### ISSUE THREAD

**Issue by BigKitten** [HasangerGames/suroi#122]
**Describe the bug**
The water tank's texture shows it to be rounded at the edges, however it's hitbox is not so you cannot go against them.

**To Reproduce**
1. Play the game
2. Find a water tank
3. Attempt to go against the corners
4. Notice that you cannot

**Expected behavior**
The water tank's hitbox should match the texture's corners.

**Comment by Katloo24** [comment]
This is intentional as we only have support currently for rectangular and circular hitboxes. Custom hitboxes will be added in the future.

**Comment by leia-uwu** [comment]
actually i found a way to do it without complex polygon hitboxes by just using circles and rectangles lol
![image](https://github.com/HasangerGames/suroi/assets/69596237/e5a07328-003a-4c67-9854-818ccdb6f499)

**Comment by BigKitten** [comment]
nice lol
