### ISSUE TITLE
Kill Leader Mechanic

### ISSUE THREAD

**Issue by JoeSquared777** [HasangerGames/suroi#177]
First off, great last update, felt a lot more like surviv.io then previous versions.
Not sure if the kill leader mechanic is supposed to work like this, but the when the kill leader is killed, the mechanic still shows them as the kill leader. I've seen it work properly a couple times, so I'm not sure what the problem is. Maybe it's supposed to work so whoever has had the most kills shows up (whether dead or alive) or whether you only wanted to show the current _alive_ kill leader. (right now it's showing whoever has had the most kills, whether or not they are alive or not) Hope this feedback helps!!

**Comment by Katloo24** [comment]
We are aware that the kill leader mechanic is bugged.

**Comment by JoeSquared777** [comment]
Okay, didn't see an issue about it, so I decided to create one. Sorry about that.

**Comment by hsanger** [comment]
Fixed

**Comment by JoeSquared777** [comment]
Yup, works like a charm now!!! If you'd like any recommendations or bug
testing, I'd love to help!! (I'm not very good at coding...)
