### ISSUE TITLE
Several suggestions for the game

### ISSUE THREAD

**Issue by internoob1** [HasangerGames/suroi#187]
Hello! I recently tried this game and I really loved how they were able to recreate something very similar to surviv.io. I know the game is in beta but I still want to recommend a few things to add:

1. An account system
Simple and easy an account system (even if it is in beta) where you can register and save your account, with the stats of kills, wins, etc. In addition to allow you (as in the original surviv) to be able to save your skins and other things. Moreover I recommend to add also for those who registered in the beta to give them some special skin, for having supported the project from the beginning.

2. A duo and squad mode
To have a good time with friends and have fun playing some games.

3. A buddy system
If they create an account system, they can identify themselves with an ID or with your name to add friends.

4. An application for pc
Instead of playing it only on google, there should be a way to download it and be able to have it in application. Since google is usually poorly optimized and usually runs poorly.

5. Airdrop system
That when the first zone is closed, or the zones are closed, airdrops fall and in this way to be able to find more rare and op loot.

6. Grenade mechanics
Add a system of fragmentation grenades, flash grenades, and smoke grenades. Since the game from what I saw in mechanics is a bit clumsy, because it is very difficult to attack a person without having to go head on and die.

7. A more complete map
I know it's in beta but it's something I recommend for next updates. I suggest that they make houses with subway areas (such as surviv) and areas of nightclubs, super markets, and other things. To make the map more beautiful to explore

I'm sorry if I got too excited suggesting so much haha, but when I saw this and you usually pay attention to your community, I was happy and wanted to suggest some things that would be missing in the game to at least make me happy.
I hope you read this and wish you luck with your project. It looks very promising!

**Comment by 1092384** [comment]
These aren't suggestions, all of them will be added except for 3 and 4.

Also, please check the discord announcements and roadmaps before making a suggestion here.

**Comment by ChpssCode** [comment]
Thank you for the suggestions however and we do take them into consideration. Please read the discord messages from now on however. Thank you!
