### ISSUE TITLE
Disable Mobile Controls Glitch

### ISSUE THREAD

**Issue by juandalequangledangle** [HasangerGames/suroi#195]
**Describe the bug**
When clicking with a mouse on disabled mobile controls, it brings up the aim line and mobile joystick, and the character looks to the right, making the game almost unplayable for users with a mouse on mobile. 

**To Reproduce**
1. Go to settings, and click on disable mobile controls, on a mobile device with a mouse and keyboard connected.
2. Reload the page, join a game, then left click.          
3. See error

**Expected behavior**
Left clicking should either cause the character to hit, or fire a weapon in the direction the mouse cursor is, without bringing up the mobile joystick and aim line, or rotating the character.

**Desktop (please complete the following information):**
 - OS: iPad OS 17.2
 - Browser: Safari
 - Version 0.12.1

**Comment by hsanger** [comment]
Noted. This will be fixed in the next update

**Comment by leia-uwu** [comment]
Fixed
