### ISSUE TITLE
Error finding game. Please try again. (Self Hosted)

### ISSUE THREAD

**Issue by AeroSouls** [HasangerGames/suroi#221]
unable to load hosted server
Hosted on linode pointed to proxy for dns.

br.itbros.gg

Config Client:
GNU nano 6.2                                  client/src/scripts/config.ts
export const Config = {
    regions: {
        dev: { name: "ITB Battle", address: "br.itbros.gg", https: true },
        na: { name: "NA Public", address: "na.suroi.io", https: true }
    },
    defaultRegion: "na",
    mode: "winter"
} satisfies ConfigType as ConfigType;

export interface ConfigType {
    readonly regions: Record<string, {
        readonly name: string
        readonly address: string
        readonly https: boolean
    }>
    readonly defaultRegion: string
    readonly mode: string
}

Config Server:

......
export const Config = {
    host: "0.0.0.0",
    port: 8000,

    mapName: "main",

    spawn: { mode: SpawnMode.Random },

    maxPlayersPerGame: 80,
    maxGames: 3,
    ..................
 

Google console log:
.......
main-fh98jROC.js:52 Could not load player count for br.itbros.gg.
(anonymous) @ main-fh98jROC.js:52
Promise.catch (async)
r @ main-fh98jROC.js:52
(anonymous) @ main-fh98jROC.js:52
(anonymous) @ main-fh98jROC.js:52
wt @ vendor-AjI_24a3.js:10
le @ vendor-AjI_24a3.js:10
setTimeout (async)
(anonymous) @ vendor-AjI_24a3.js:10
I @ vendor-AjI_24a3.js:10
fireWith @ vendor-AjI_24a3.js:10
fire @ vendor-AjI_24a3.js:10
I @ vendor-AjI_24a3.js:10
fireWith @ vendor-AjI_24a3.js:10
ready @ vendor-AjI_24a3.js:10
setTimeout (async)
.......

**Comment by AeroSouls** [comment]
> Strange, it works fine for me

you can connect to ITB Battle ?

**Comment by AeroSouls** [comment]
![image](https://github.com/HasangerGames/suroi/assets/49828953/c805c187-b408-4a31-848e-7bc44c314779)
Also getting this error when trying to join public NA

**Comment by hsanger** [comment]
> you can connect to ITB Battle ?

Yes, it works fine for me
