### ISSUE TITLE
Airdrops can fall on each other

### ISSUE THREAD

**Issue by ersek-huba** [HasangerGames/suroi#280]
**Describe the bug**
When you summon two airdrops at the same position, one will fall on the other one.

**To Reproduce**
Summon two airdrops at the same position using radios.

**Expected behavior**
The secondly summoned airdrop is pushed away by the firstly summoned airdrop.

**Additional context**
I think this is caused by the "summonAirdrop" function, in the server's "Game" class.

**Comment by 1092384** [comment]
I believe this is already fixed.

**Comment by Compositr** [comment]
@1092384 status update on duos update?

**Comment by 1092384** [comment]
@Compositr @boronkay-tanulo Apologies for the miscommunication, I have tested this and came to the conclusion that this bug is indeed still relavent in the duos update. The devs will address this bug as soon as possible.

**Comment by ersek-huba** [comment]
As I see, it's fixed now, so I'm closing this.
