### ISSUE TITLE
The game server shouldn’t send the position of objects inside buildings

### ISSUE THREAD

**Issue by DrMinh** [HasangerGames/suroi#307]
Sorry that I have not read the source code yet, but it appears that the game server sends the position of the player under the roof to the client. Some cheaters simply remove the roof graphics, allowing them to see players inside. I believe that when something is fully covered, it should be completely invisible. While this change may not significantly reduce cheating, it is still an improvement.

**Comment by CroissantEdit** [comment]
This is known for a bit, samethings with bushes  tables, and smoke. One of the dev made a hack client with it 💀💀

**Comment by Viswas-Programs** [comment]
This cant be done, see because some of the house roofs have these transparent areas where the player can be seen by default
So if you dont send player positions to the clients those transparent areas would be useless
And to remove those areas is upto the developers.

**Comment by leia-uwu** [comment]
also sounds depend on objects being sent to the client, for example you will only hear a player walking inside the house if the player inside the house is sent to the client
