### ISSUE TITLE
Objects can be destroyed while not looking at them

### ISSUE THREAD

**Issue by NoLongerLucky** [HasangerGames/suroi#31]
**Describe the bug**
Objects can take damage and be destroyed while the character isn't facing towards them.

**To Reproduce**
1. Go to an object and make sure you are touching it
2. Rotate your character to face in the opposite direction of the object
3. Click to punch
4. The object will take damage even though the fists are punching in the opposite direction

**Expected behavior**
The object should only take damage when the player is punching toward it.

**Screenshots**
![image](https://github.com/HasangerGames/suroi/assets/44245434/95ff2213-179d-4b33-a2a9-b238451b3550)
The box was damage while the player is facing away from it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: v0.1.0

**Additional context**
N/A

**Comment by leo78913** [comment]
Fixed :p
