### ISSUE TITLE
Unhinged Solos

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [HasangerGames/suroi#354]
Think of it like this, you go around playing queued solos to where you encounter another player.
You have two options, kill them, or invite them to the team.
The Team Size is dynamic and will grow to a max of three players for a team. 
However Players in a team can join other teams and betray each other, which is the point of a dynamic team.
Last team standing wins.

Something I've wanted to bring up, just want to see what you guys think.

**Comment by ersek-huba** [comment]
This is just stupid. Solo is a game mode where you supposed to be alone, and fight other players on your own. Teaming with other players gives you advantage over the other players, who are playing alone.

**Comment by ZEROPOINTBRUH** [comment]
The purpose of unhinged solos is to either fight along side with random players you meet alongside giving people the sense of trust or betrayal, either to fight alone, or fight together. However these teams are dynamic, you can choose to either stay with who your with, or join another team in the meantime. Making the fights stretch out more dynamically in chaos. You can either fight together or fight alone. Noobs will like this mechanic as it gives them a chance to work together with other players who may or may not be more experienced with other players who may have played the game longer. For people who are more experienced within the game they can choose to work together with the players or die alone. 

However you cant just add everyone in the lobby as dynamic teams should be locked behind a limit of 3 players per team. Starting off people in solos and building groups later on in the games with randoms within the server.

**Comment by AshMyBoi** [comment]
> This is just stupid. Solo is a game mode where you supposed to be alone, and fight other players on your own. Teaming with other players gives you unfair advantage over the other players, who are playing alone.

I agree

**Comment by JoanneFractalHacker** [comment]
Heads up, Trump was shot. A warning shot It missed and scraped his ear. From: Ash ***@***.***>Sent: Saturday, July 13, 2024 5:36:56 PMTo: HasangerGames/suroi ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [HasangerGames/suroi] Unhinged Solos (Issue #354)

This is just stupid. Solo is a game mode where you supposed to be alone, and fight other players on your own. Teaming with other players gives you unfair advantage over the other players, who are playing alone

I agree

**Comment by DamienVesper** [comment]
This isn't something we're looking to implement as of right now. If our team plans to revisit this topic later, we will let you know.
