### ISSUE TITLE
using the map ping wheel keybind switches the emote wheel to map ping mode

### ISSUE THREAD

**Issue by mse-k** [HasangerGames/suroi#394]
**Describe the bug**
there is a keybind to switch between the emote wheel being a map ping an emotes, but theres also a keybind to quickly open up the map ping wheel by itself. as i had done in surviv.io, i bound map ping to middle click and emote to right click, that way i could easily use both for any situation, but unfortunately this doesnt work.

**To Reproduce**
1. bind both "Emote Wheel" and "Map Ping Wheel"
2. enter the game and use the emote wheel key (works as expected, opens the emote wheel)
3. use the map ping wheel key (also works as expected, opens the map ping wheel)
4. use the emote wheel key again (it opens the map ping wheel instead of the emote wheel, effectively turning both keys into map ping wheel keys)

**Expected behavior**
the emote wheel should open when i press the emote wheel button and the map ping wheel should open when i press the map ping wheel button. the behavior of converting the emote wheel into a map ping one should only occur when using "Switch to Map Ping" key, and not the instant map ping wheel key.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: unsure, but i hard reloaded on the page and it persists

**Comment by ei-pi** [comment]
fixed
