### ISSUE TITLE
Modes not swithcing

### ISSUE THREAD

**Issue by Hashimk2** [HasangerGames/suroi#433]
“This is the harvest changelog”
[v0.21.5](https://github.com/HasangerGames/suroi/releases/tag/v0.21.5) Pre-release
Updated rules

The game's rules have been updated. Please head over to https://suroi.io/rules and read them.

Changes

Harvest mode is over. The game now switches between modes once per week.
Major code refactors.
New pine tree sprite.
Improved animations for melee weapons.
Rebalanced Flues.

This is the v0.21.5 update when normal mode returned from harvest mode. It literally says that the game modes switch every week after November 11th, but the mode stays normal. Why is this? Same thing for the winter mode, it is only stuck at the winter mode when it says in the changelog that rotating modes will begin on December 15th, today is the 17th.

**Comment by emeraldn30** [comment]
"Unfortunately, mode rotations weren't finished on time and will be delayed by a few days. Sorry for the wait."

**Comment by Hashimk2** [comment]
It has been four days since the modes were supposed to rotate

**Comment by Hashimk2** [comment]
> "Unfortunately, mode rotations weren't finished on time and will be delayed by a few days. Sorry for the wait."

Why do you have it in quotes?
Does it say somewhere else?

**Comment by emeraldn30** [comment]
1. The modes will be rotating weekly once the code for it is finalized 
2. Yes, this information is repeated in the Suroi discord server. If you would have checked there you wouldn't have needed to make this post.

**Comment by Hashimk2** [comment]
> 1. The modes will be rotating weekly once the code for it is finalized
> 2. Yes, this information is repeated in the Suroi discord server. If you would have checked there you wouldn't have needed to make this post.

I dont have discord.
