### ISSUE TITLE
I’m not sure if this is my computers problem or with the website

### ISSUE THREAD

**Issue by kidwaih2** [HasangerGames/suroi#442]
When you select the servers on suroi.io, the top one is localhost server, but when i click it and play solo, squads or duos, it says, 'error finding game'
![IMG_4572](https://github.com/user-attachments/assets/49a36ebb-c8c5-4fe8-9a87-d68e4844527d)

**Comment by DamienVesper** [comment]
Localhost isn't supposed to be on there. Looks like there was a mistake while deploying.
Use NA, EU, SA, or AS regions instead.

**Comment by kidwaih2** [comment]
> Localhost isn't supposed to be on there. Looks like there was a mistake while deploying. Use NA, EU, SA, or AS regions instead.

Oh ok. Thank you very much

**Comment by yinxq001** [comment]
Excuse me, how exactly did you solve the problem? It was also the problem when I built it myself.
