### ISSUE TITLE
Im not sure if this is an issue, or is it just for a joke?

### ISSUE THREAD

**Issue by kidwaih2** [HasangerGames/suroi#446]
**Describe the bug**
In the language dropdown menu, one of the languages is the HP-18 along with the loot picture of the HP-18
When you play the game, all guns and almost every word that is on the screen says HP-18.

**To Reproduce**
1. Go to https://suroi.io/
2. Click on languages
3. At the top, one of the languages is HP-18, instead of a flag beside it, the HP-18 loot image is shown
4. Play the game, hover over an object or door, and see the error

**Expected behavior**
No language is HP-18 (unless this is meant as a joke)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: All versions
 - Browser: All browsers
 - Version: All versions

**Picture**
![Screenshot (760)](https://github.com/user-attachments/assets/4b43af3a-a044-4f17-a60d-46bc2025d928)
![Screenshot (759)](https://github.com/user-attachments/assets/0d571653-b779-4027-988d-89ac8b1266f4)

This is not an issue to me as I play in english

**Comment by kenos1** [comment]
https://github.com/HasangerGames/suroi/blob/21db3ae55a9c8c74e2884919c3cf9867c46cb251/client/src/translations.ts#L83

**Comment by kidwaih2** [comment]
Thank you

**Comment by ersek-huba** [comment]
I can't believe you didn't get the joke (can you close this now?)

**Comment by kidwaih2** [comment]
> I can't believe you didn't get the joke (can you close this now?)

I was just making sure
