### ISSUE TITLE
is there an europe server of suroi?

### ISSUE THREAD

**Issue by darik9pl** [HasangerGames/suroi#53]

**Comment by hsanger** [comment]
A Europe server will likely be created soon.

Not an issue, closed.

**Comment by darik9pl** [comment]
ok

**Comment by darik9pl** [comment]
> A Europe server will likely be created soon.
> 
> Not an issue, closed.

is the europe server done?

**Comment by darik9pl** [comment]
> A Europe server will likely be created soon.
> 
> Not an issue, closed.

also, please block leo78913 because he bullied me

**Comment by DamienVesper** [comment]
> > A Europe server will likely be created soon.
> > Not an issue, closed.
> 
> also, please block leo78913 because he bullied me

damn you let yourself be bullied
