### ISSUE TITLE
note

### ISSUE THREAD

**Issue by darik9pl** [HasangerGames/suroi#57]
is the europe server done

**Comment by darik9pl** [comment]
also block leo78913

**Comment by hsanger** [comment]
No, the Europe server is not done yet.
This is not the place to ask questions. If you have a question, ask on the Discord server: https://discord.suroi.io
Not an issue, closed.

**Comment by darik9pl** [comment]
> No, the Europe server is not done yet. This is not the place to ask questions. If you have a question, ask on the Discord server: https://discord.suroi.io Not an issue, closed.

bro i dont have a discord

**Comment by darik9pl** [comment]
i dont have reddit

**Comment by darik9pl** [comment]
but i created a one

**Comment by darik9pl** [comment]
heres how my reddit avatar looks like
![downloadable-db40a6d7-bdcf-4f54-bd37-af462250dbf9](https://github.com/HasangerGames/suroi/assets/114980083/1a353ae8-6988-4c17-901d-661c161bd7c0)
