### ISSUE TITLE
Client Debug unbound breakpoint 

### ISSUE THREAD

**Issue by meiry** [HasangerGames/suroi#95]
How do you setup vscode to debug the client ? 
i keep getting : unbound breakpoint

**Comment by DamienVesper** [comment]
Not sure what you mean, could you be more specific?

**Comment by Killaship** [comment]
Can someone close this (or give me the ability to)? It's been sitting for 2 weeks until a few days ago, with no responses from the OP. I think it might be an issue with their configuration, but in any case, this issue probably won't be fixed in any reasonable amount of time.
